quil-lang/qvm

src/density-qvm.lisp, src/measurement.lisp, src/qam.lisp, src/transition.lisp
=> Makes classical bit param in measure optional

Makefile
We might as well do this for the qvm too. 
Also it feels a bit silly to use both DESTDIR and PREFIX, but e.g. it is suggested here https://www.gnu.org/prep/standards/html_node/DESTDIR.html
=> Add install/uninstall from makefile

tests/gate-tests.lisp, tests/instruction-tests.lisp, tests/measurement-tests.lisp, tests/modifier-tests.lisp, tests/suite.lisp, tests/utilities.lisp
=> don't run all tests in both modes

app/src/entry-point.lisp
=> log to stderr

app/src/entry-point.lisp, app/src/utilities.lisp, doc/man/qvm.1
=> make execute mode default

app/src/entry-point.lisp
=> Undelete default-allocation option

build-app.lisp
cf https://github.com/rigetti/quilc/pull/165
=> compress core if compression is available

src/qvm.lisp
Should not be merged into the Quilc patch https://github.com/rigetti/quilc/pull/141 is merged.
=> do patch-labels in load-program

build-app.lisp, qvm-app.asd, qvm.asd
and #:trivial-features ':windows elsewhere
=> Use ':win32 in build-app.lisp

src/compile-gate.lisp, src/density-qvm.lisp, src/depolarizing-noise.lisp, src/execution.lisp, src/noisy-qvm.lisp, src/qam.lisp, src/qvm.lisp, src/transition.lisp, tests/instruction-tests.lisp
This enable's CL-QUIL's fusion abilities, and adds measure chain collapse to `-c` mode.
=> enable gate fusion and measure chain optimization

src/qvm.lisp
Closes #78.
Depends also on this: https://github.com/rigetti/quilc/pull/209
=> Fix broken QFT benchmark

app/src/entry-point.lisp, app/tests/suite.lisp, app/tests/utils.lisp, qvm-app-tests.asd
=> Fix the fix that tests server startup

Dockerfile, README.md
Akin to [rigetti/quilc#233](https://github.com/rigetti/quilc/pull/233).
=> EXPOSE the default qvm server port in the Dockerfile

qvm-app.asd, qvm.asd
Small beans, but it is what it is.
=> Bump cl-quil dependency

Makefile
=> Use $(QUICKLISP) in Makefile's clean-cache target

scripts/prof.lisp
modified:   scripts/prof.lisp
The program used for profiling is now created by parsing a string.
The previous implementation depended on details of addressing memory
of the qvm. These details have changed since this profiling code was
last edited.
=> Update performance test for changes in memory model

app/src/entry-point.lisp
=> Add missing space in command line help message.

dqvm/Makefile, dqvm/src/master.lisp, dqvm/src/worker.lisp
Update DQVM code so that it compiles and runs.
=> Get DQVM back running.

dqvm/src/common.lisp, dqvm/src/main.lisp
=> Remove dynamic variable *program* (fixes #16).

app/src/entry-point.lisp, doc/man/qvm.1, src/apply-gate.lisp, src/compile-gate.lisp, src/config.lisp, src/qvm.lisp, tests/suite.lisp
Incorporates the last of https://github.com/rigetti/qvm/pull/55
More importantly, this adds a `-O` option to change the QVM's aggression in compilation optimization.
```
-O 0   # disables compilation
-O 1   # some light compilation
-O [>1] # show me wut u got
```
=> incorporate last vestiges of other compilation PR

src/apply-gate.lisp, tests/modifier-tests.lisp
=> Simulate FORKED-GATEs

app/src/benchmark-programs.lisp, app/src/entry-point.lisp, doc/man/qvm.1
=> Fix qulacs spelling error

src/density-qvm.lisp
=> fix #140 a good deal

src/impl/sbcl-avx-vops.lisp
In response to https://github.com/rigetti/qvm/pull/157#discussion_r316378527
=> Add movable tag to %2x4matrix-to-simd

src/density-qvm.lisp
=> density-qvm: provide missing kwargs to DENSITY-QVM

.github/workflows/test.yml, Makefile, src/impl/sbcl.lisp
=> Use github actions for tests, and fix undefined functions in static-allocations

src/linear-algebra.lisp
Change-Id: I796bfffbaff2af3d607c94ae71b1c7de364992fd
Reviewed-on: https://gerrit.franz.com:9080/c/qvm/+/19672
Reviewed-by: Tianyu Gu <gty@franz.com>
Reviewed-by: Kevin Layer <layer@franz.com>
Tested-by: Kevin Layer <layer@franz.com>
=> temporary LOOP macro fix for AllegroCL

Makefile
=> Bump dynamic space size to 4GB when building qvm executable

qvm.asd, src/error/fowler-noise.lisp, src/error/package.lisp, src/package.lisp
See also [this PR](https://github.com/quil-lang/quilc/pull/919) to quilc.
=> updated to use clos-encounters
