quil-lang/qvm

- .gitlab-ci.yml
- CODEOWNERS
- Makefile
- README.md
* Include the [`rigetti/ci`](https://github.com/rigetti/ci) docker job pipeline template rather than redefining
* Add `README` notes about the [`rigetti/qvm`](https://hub.docker.com/r/rigetti/qvm) Docker image and how to use it
* Add `README` notes about the release process
* Add a `CODEOWNERS` file for default/required reviewers
> Various improvements to the CI infra and release process

- doc/editing-and-running.md
This eliminates the warning about coercing to directory.
> Add a trailing slash in the quickproject example

- README.md
- app/src/api/multishot-measure.lisp
This parameter was removed by a previous
PR (https://github.com/rigetti/qvm/pull/23).
> Remove nil from qvm:measure calls

- Makefile
- app/src/mangle-shared-objects.lisp
- build-app.lisp
- doc/lisp-setup.md
Instead, use build-app.lisp file to load QVM and save the qvm
application file.
Currently only SBCL support is implemented.
> Remove use of buildapp per #33

- app/src/benchmark-programs.lisp
- app/src/entry-point.lisp
- doc/man/qvm.1
Adds the benchmark proposed [here](https://github.com/qulacs/qulacs).
I think this is a great benchmark for improvements to compiled mode, mostly because it has huge layers of 1q/2q gates.
> add qualcs benchmark

- app/src/api/multishot-measure.lisp
- app/tests/suite.lisp
- src/measurement.lisp
- tests/measurement-tests.lisp
`qvm:measure` was absolutely not type safe. It allowed very dangerous calls which led to failing tests in OOB memory accesses.
The `qvm:measure` generic function accepted any `q` which was blindly passed to `force-measurement`, which was optimized dangerously. This plugs that hole, but I wonder what else is lurking.
> make MEASURE type safe

- README.md
- app/src/benchmark-programs.lisp
- app/src/configure-qvm.lisp
- app/src/entry-point.lisp
- app/src/globals.lisp
- app/tests/suite.lisp
- doc/man/qvm.1
- dqvm/src/worker.lisp
- qvm.asd
- src/allocator.lisp
- src/density-qvm.lisp
- src/floats.lisp
- src/impl/sbcl.lisp
- src/linear-algebra.lisp
- src/noisy-qvm.lisp
- src/package.lisp
- src/qvm.lisp
- src/shm.lisp
- src/wavefunction.lisp
- tests/linear-algebra-tests.lisp
- tests/measurement-tests.lisp
- tests/noisy-qvm-tests.lisp
- tests/stress-tests.lisp
- tests/utilities.lisp
- tests/wavefunction-tests.lisp
This adds an ALLOCATE-VECTOR and a host of different allocation modes.
This commit doesn't actually incorporate it into the actual API,
however, which will come in later commits.
TODO:
> initial interface for different kinds of allocations

- app/src/entry-point.lisp
e.g. using --host 127.0.0.1 restricts incoming connections to those
from localhost
> Configure host with --host

- app/src/entry-point.lisp
- app/tests/suite.lisp
Or rather, *only* start server if `-S` is provided. Closes #77.
> Don't start server if only -p is provided.

- tests/stress-tests.lisp
- tests/utilities.lisp
This way the test itself is always present, but the body of the test may not be.
> skip unix/sbcl tests on windows/non-sbcl

- examples/qft.lisp
- src/compile-gate.lisp
- src/depolarizing-noise.lisp
- src/noisy-qvm.lisp
- src/transition.lisp
- tests/gate-tests.lisp
This fixes some backwards incompat. changes from cl-quil.
These changes also cause a performance regression in the runtime of the QVM. Namely:
- For rotation gates, `sin`, `cos`, and `/` are computed 2x more often.
- For permutation gates like `CNOT`, it's no longer recognized that they're permutations, so the qvm runs them far more inefficiently.
The latter causes the bigger perf regression, and should be solved with @notmgsk's pending PR to quilc.
> fix breakage due to feature/lifting in cl-quil

- src/density-qvm.lisp
In rigetti/quilc#224, the DIMENSION slot was moved out of the GATE
class and into the PARAMETERIZED-GATE class. As a result, :DIMENSION
is no longer a valid initarg for SIMPLE-GATEs and PERMUTATION-GATEs.
> Nix :DIMENSION when constructing SIMPLE-GATE or PERMUTATION-GATE

- app/src/entry-point.lisp
- app/src/qvm-app-version.lisp
The changes here are three:
1. Catch USOCKET:NS-ERROR and USOCKET:SOCKET-ERROR when checking for an SDK update. Originally we caught USOCKET:NS-HOST-NOT-FOUND-ERROR, but this allowed other related errors through, causing the app to crash.
2. Provide --proxy to be used by quilc::latest-sdk-version and those behind network restrictions. This one makes me slightly uncomfortable, since it may be confused with providing a proxy for the server itself.
3. Replace the off-by-default --skip-version-check with the off-by-default --check-sdk-version. Network issues may cause the app to crash or be slow while waiting for the update check to finish; IMO this should be opt-in. Also, this option now causes the program to exit (with an appropriate return code).
Closes #86 and #88.
> Provide --proxy, catch usocket errors, SDK check off by default

- .gitignore
system-index.txt is generated by quicklisp
> Add system-index.txt to .gitignore

- qvm-tests.asd
- src/utilities.lisp
- tests/parallel-tests.lisp
This PR is a step towards making tuning the number of threads more flexible.
This commit improves the behavior of prepare-for-parallelization.
The following are corrected:
* The message given by the assert call may be inaccurate when calling
prepare-for-parallelization twice with different arguments.
* The doc string refers to the function by the wrong name.
Furthermore, calling prepare-for-parallelization once and then
calling it again with a different argument now changes the number
of threads. More precisely, the existing thread pool is freed and
a new one is created only if the number of threads requested differs
between the two calls.
The existing test suite passes. But this PR needs tests.
> [wip] Allow changing the number of threads in thread pool

- doc/lisp-setup.md
This parrot is no more!
https://github.com/slime/slime/commit/7d17bb1e5881f1d3ca11ba25af60cd64896c2ee6
> Remove SLIME-MULTIPROCESSING from lisp-setup.md

- src/compile-gate.lisp
The purpose of this is to explore optimizations in memory accesses for the QVM.
> change how wf elements are extracted for gate applications in -c

- app/src/benchmark-programs.lisp
- app/src/entry-point.lisp
- doc/man/qvm.1
allows `--benchmark-type baseline`
> add baseline benchmark, remove computing it by default

- src/classical-memory-mixin.lisp
This was fixed in #81 but somehow found it's way back in, possibly due to a bad rebase/merge.
> Fix QFT benchmark

- src/execution.lisp
Fixes a divide by zero when no instructions are fed to qvm with `-c` and `--verbose` enabled.
Also adds a newline to fix formatting when transition times are not printed (such as in the case of no instructions.)
> Fix divide by zero on no instructions and add newline

- qvm-tests.asd
- qvm.asd
- src/linear-algebra.lisp
- src/package.lisp
- src/subsystem.lisp
- src/utilities.lisp
- src/wavefunction.lisp
- tests/subsystem-tests.lisp
This PR introduces a new basic data type: `SUBSYSTEM`. This is similar to ecp's asocial qvm stuff; this is intended to be the foundation to supporting disconnected qubit systems without hacking it on the current QVM.
Eventually, the QVM's state—`amplitudes`—will instead use a collection (possibly 1) of these.
> Qubit subsystems

- Makefile
This fixes the app-ng tests which are failing when run with `make test`.
> Add intrinsics feature to app-ng tests

- build-app-ng.lisp
- build-app.lisp
Fix for #168 
Disable call to zap-info in app build
> Fix building with SBCL 1.5.6

- LICENSE.txt
I'm not sure if this needs to happen since the intention is for qvm-app-ng to be temporary and eventually replace qvm-app, but figured it's worth bringing up. If we do merge this, we'll need to file an issue to remember to undo it when qvm-app-ng becomes qvm-app.
> Add app-ng directory to LICENSE.txt spiel

- app/src/entry-point.lisp
- app/src/globals.lisp
- app/src/handle-request.lisp
> Work around out of memory issue with foreign allocator.

- app/src/entry-point.lisp
- app/src/handle-request.lisp
The garbage collection added at the end of HANDLE-REQUEST in #199 prevents HANDLE-REQUEST from returning a value. Some of the handlers write to the response stream directly, but others just return a value, which hunchentoot handles sending back to the client.
> Ensure that a value is returned from HANDLE-REQUEST

- src/channel-qvm.lisp
- src/noise-models.lisp
- tests/channel-qvm-tests.lisp
#210 
The channel-qvm expects its :noise-model slot to be a noise-model object, but it's default initarg is nil. This causes errors when a channel-qvm is created without a defined noise-model argument. To fix this I: 
- changed the default noise-model initarg of `channel-qvm` to be a `noise-model` with an empty set of noise-rules
- I added a check to `initialize-instance` to ensure that the `noise-model slot of `channel-qvm` is of type `noise-model`
- added checks to a test in `tests/channel-qvm`
> changing the default :initarg of channel-qvm to be valid

- tests/gate-tests.lisp
This is mostly a sanity check.
> Add xy test

- examples/qaoa.lisp
- qvm-examples.asd
- src/wavefunction.lisp
this adds a small example to run QAOA and also plot the cool landscape plots
> QAOA and MAXCUT landscape plotting

- Dockerfile
~~Attempting to resolve `-edge` build failures like [this one](https://gitlab.com/rigetti/forest/qvm/-/jobs/372229634) by updating quicklisp dependency. Too lazy to test docker builds locally, pls ignore for now. kthanxbye.~~
Resolve `-edge` build failures like [this one](https://gitlab.com/rigetti/forest/qvm/-/jobs/372229634) by updating the quicklisp dependency.
QVM itself does not require the latest quicklisp, but quilc does because of it's recent magicl update to 0.6.5 (I think).
> Update quicklisp_version to 2019-11-30 in Dockerfile

- app/src/configure-qvm.lisp
- dqvm/tests/program-tests.lisp
Before the qvm state representation refactor, `:AMPLITUDES` was an initarg for the different QVM classes to store the wavefunction data of a qvm. This functionality is now replaced by the QVM's `STATE`, and `:AMPLITUDES` is no longer a valid initarg for any QVM. This PR changes the `QVM-APP` to call the `:STATE` initarg instead of the `:AMPLITUDES` initarg when `make-instance`ing a QVM. 
This could possibly be more cleanly fixed by having more elegant `make-xxx-qvm` functions that can take pre-allocated amplitudes as arguments for the different types of QVMs. Since these functions do not exist, the QVM-APP uses `make-instance` when creating a QVM with an already allocated amplitudes vector.
> removing old :AMPLITUDE initarg references in qvm-app

- app/src/benchmark-programs.lisp
- app/src/entry-point.lisp
- app/src/globals.lisp
- app/src/handle-request.lisp
- app/tests/suite.lisp
- examples/qaoa.lisp
Apologies for this late PR. This removes some code duplication by using directly cl-quil's functions for safe resolution of include files.
> Use cl-quil's tools for safe resolution of included files

- qvm-app.asd
Update qvm-app cl-quil dep to match that of qvm since qvm-app now depends on `cl-quil:safely-parse-quil`
> Bump cl-quil dependency in qvm-app.asd

- Makefile
I'm not *entirely* sure why I was seeing the following behaviour, but this PR fixes it.
At the top of `Makefile`, `$LISP_CACHE` is defined using backtick notation. Later, in the `clean-cache` target, `$LISP_CACHE` is used twice: once in an `echo`, and once in a `rm`. In the `echo`, the path is displayed properly, but in the `rm` it looks like the backticks are not evaluated, and instead the command is ``rm `sbcl ...` `` which results in an error.
> Wrap variable in quotes, in Makefile

- Makefile
- build-app.lisp
This prevents the annoying situation where you've loaded e.g. drakma in your REPL with SSL enabled, and after that when you try to compile quilc you get the error about being unable to find the CL+SSL package.
Same change was made to quilc.
Closes #72.
> Only disallow SSL for SDK builds

- app/src/configure-qvm.lisp
The function `CL-QUIL::MAKE-ROW-MAJOR-MATRIX` was removed in https://github.com/rigetti/quilc/pull/574.
Switch to using `MAGIC:FROM-LIST`, instead.
> EXTRACT-KRAUS-OPS: CL-QUIL::MAKE-ROW-MAJOR-MATRIX -> MAGICL:FROM-LIST

- app-ng/tests/test-rpc-api.lisp
Previously, tests that waited for a `PERSISTENT-QVM` or `JOB` to reach a particular state would just blindly loop repeating the request and hope for the best. This commit adds a `WAIT-FOR` function that retries the request with an increasing backoff delay between failures.
I don't know if http requests suddenly got faster or if something in the QVM suddenly got slower, but I noticed the wait/resume test suddenly started failing on my laptop without this change.
> Retry with backoff when waiting for a given state in app-ng tests

- Makefile
When attempting an install of QVM with a custom value for the PREFIX variable, the installation command assumes that `$(DESTDIR)$(PREFIX)/bin` exists. However, this is may not always be the case, leaving the `qvm` and `qvm-ng` binaries being copied to `$(DESTDIR)$(PREFIX)/` as `bin`-named binaries, overwriting one another respectively.
As a fix for this, I have added a line to create the required `bin` directory if it does not yet exist. For installations into existing PREFIX directories (e.g `/usr/local/`) there will be no change, but for `PREFIX` dirs without a `bin` directory one will be created before installing the binaries.
> Create PREFIX/bin/ dir during `make install` if does not exist

- Dockerfile
This was an oopsie. The `make install` was being treated as a separate build, not inheriting the appropriate `${build_target}` and so it was re-built and then installed as a standard non-sdk build.
> Fix build error

- app/src/build-configuration.lisp
- build-app.lisp
- src/apply-gate.lisp
- src/compile-gate.lisp
- src/config.lisp
This PR decreases the amount of cache warming when the QVM system is compiled to just 8 qubits, which takes around 1.5 seconds on my old laptop on battery. However, when the executable is built, we cache for up to 30 qubits.
> lower default QVM operator cache limit, add caching to executable

- src/measurement.lisp
This addresses #277 
The approach used for generating Bernoulli random variables is "inverse transform sampling", which would work fine if `(random 1d0)` was "truly" uniform. Since we have only 53 bits of precision, even a perfect implementation of `(random 1d0)` would give a (1/2)^53 chance of producing a `0`. On that fateful day, when the planets align and the birds by sheer coincidence begin singing in unison, some poor sob will run a deterministic circuit and get back just the opposite of what was expected. But nobody will have told our unsuspecting QC enthusiast that it was, in fact, Opposite Day.
This is an easy fix at least. With the current method of `<=` comparison we just handle the zero probability case explicitly. We end up with two conditions met:
1. preserve the general …
> Handle finicky corner case of deterministic measurements

- qvm-app.asd
- qvm-tests.asd
- qvm.asd
- src/channel-qvm.lisp
- src/compile-gate.lisp
- src/depolarizing-noise.lisp
- src/noise-models.lisp
- src/package.lisp
- src/stabilizer-qvm.lisp
- src/transition.lisp
- tests/channel-qvm-tests.lisp
- tests/package.lisp
cf. https://github.com/quil-lang/quilc/pull/761
We make some tweaks so that the `qvm` relies only on `cl-quil/frontend`. One convenient but possibly questionable choice is that we alias the package `cl-quil.frontend` to `quil`, since it's annoying to not do so.
> use cl-quil/frontend

- qvm.asd
The full magicl suite includes expokit, but we don't need it, and so should just drop it. Also, with the recent qvm-in-cl-quil work, this expokit stuff would also be required by cl-quil. This appears to be the cause of tests failing on https://github.com/quil-lang/quilc/pull/779
> drop expokit dependency

- app-ng/src/entry-point.lisp
- app/src/entry-point.lisp
- qvm.asd
- src/impl/sbcl-x86-vops.lisp
- src/serial-kernels.lisp
- src/wavefunction.lisp
* Change MAKE-EA to EA.
* Test for AVX2 in a different way, as we're not allowed to test sbcl
internal features anymore.
> Make QVM-INTRINSICS work again.

- src/apply-gate.lisp
When redefining some of the std gates as sequence gates, it was discovered that the QVM would not know how to handle these
> let qvm use sequence gates

- qvm.asd
Closes #306 . I've confirmed this change enabled a smooth build on our Ampere box.
This alone doesn't solve the ARM64 build - there are some changes needed in cffi as well, which I'll take a look at later this week.
> fix: catch unbound alien variable when building on arm64

- qvm-tests.asd
- qvm.asd
- src/depolarizing-noise.lisp
- src/error/README.md
- src/error/error-qvm.lisp
- src/error/fowler-noise.lisp
- src/error/package.lisp
- src/utilities.lisp
- tests/error-qvm-tests.lisp
The PR introduces two further variants of noisy QVMs:
1. `fowler-qvm`: A variant of `stabilizer-qvm` which injects depolarizing noise after "basic" operations. "Basic" operations are divided into types (identity, nontrivial 1Q, 2Q, measure, reset), and noise can be selectively toggled for each of these types. (I think that in the current implementation these types are explicitly given by named gates, e.g., `I` and `H`, as opposed to any ol' 1Q Clifford.) This class type is named `fowler-qvm` rather than `depolarizing-stabilizer-qvm` because of this toggling ability, which is a slightly different noise model than straight-up depolarizing noise; to our knowledge, this modified noise model was specified by Austin Fowler in work on topological error correction.
2. `error-qvm`: A restriction …
> add depolarizing stabilizer QVM and error-only QVM

- src/error/fowler-noise.lisp
Whoops: after the move from `qvm` to `qvm.error`, two of the "Fowler QVM" variants had superclasses which were missing a namespace tag.
> fix bad package qualifiers

- qvm.asd
- src/error/package.lisp
- src/package.lisp
See also https://github.com/quil-lang/quilc/pull/904
> Abstracts dep rename

- src/classical-memory.lisp
Minor nit: changes error message from
The value of QVM::SIZE is 0, which is not The SIZE wasn't a multiple of 8..
to
The value of QVM::SIZE is 0, which is not a multiple of 8.
> Provide type description fragment in allocate-memory-for-model error
